server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: sa
    password: sa
  sql:
    init:
      schema-locations:
        - classpath:db/product-schema.sql
      data-locations:
        - classpath:db/product-data-schema.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
    web: debug
    ls.ov.ipay: debug
mybatis-plus:
  configuration:
    database-id: h2
    map-underscore-to-camel-case: true
  global-config:
    banner: false